name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - dev
      - staging
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: asdasd

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker
    - name: Set deployment info
      id: set_deployment_info
      run: |
        echo "DEPLOY_TYPE=${{ github.event.inputs.deploy_type }}" >> $GITHUB_ENV
        echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
        if [ -n "${{ github.event.inputs.custom_tag }}" ]; then
          echo "TAG=${{ github.event.inputs.custom_tag }}" >> $GITHUB_ENV
        else
          echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
        fi
    - name: Build and push Backend Docker image
      run: |
        docker build -t us.gcr.io/${{ env.GOOGLE_CLOUD_PROJECT }}/livekit-agent:latest -f Dockerfile .
        docker push us.gcr.io/${{ env.GOOGLE_CLOUD_PROJECT }}/livekit-agent:latest
    - name: Build and push Frontend Docker image
      run: |
        docker build -t us.gcr.io/${{ env.GOOGLE_CLOUD_PROJECT }}/livekit-agent:latest -f Dockerfile .
        docker push us.gcr.io/${{ env.GOOGLE_CLOUD_PROJECT }}/livekit-agent:latest
    - name: SSH into VM and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.INSTANCE_IP }}
        username: ${{ env.SSH_USER }}
        key: |
         -----BEGIN OPENSSH PRIVATE KEY-----
         b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
         QyNTUxOQAAACD8+CtyqitTXOMFOKPvRXmrKQhRIsEb+NaCWK9xFFwBGwAAAJjEIf/yxCH/
         8gAAAAtzc2gtZWQyNTUxOQAAACD8+CtyqitTXOMFOKPvRXmrKQhRIsEb+NaCWK9xFFwBGw
         AAAECjCoeULHPOVmeOal4FkdZZmEzyWV4vWaxLvxHPke4xXfz4K3KqK1Nc4wU4o+9Feasp
         CFEiwRv41oJYr3EUXAEbAAAAFW12aWthc3JlZGR5QGdtYWlsLmNvbQ==
         -----END OPENSSH PRIVATE KEY-----
        script: |
          echo "Stopping and removing old containers..."
          docker stop livekit-agent-container || true
          docker rm livekit-agent-container || true
          
          
          echo "Deploying backend..."
          docker run --env-file ~/workflows/.env -p 3000:80 --name workflow-container -d us.gcr.io/${{ env.GOOGLE_CLOUD_PROJECT }}/ai-workflow:latest
          
          echo "Deployment complete!"
